services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # for Mac/Windows live reload

  backend:
    build: ./back-end
    ports:
      - "5001:5001"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    env_file:
      - ./back-end/.env
