name: Continuous Deployment to App Platform

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Run tests
        run: |
          cd back-end
          npm install
          npm test
      
      - name: Deploy to App Platform
        run: doctl apps update ${{ secrets.APP_ID }} --spec .do/app.yaml || doctl apps create --spec .do/app.yaml